OBJ_DIR = bin/
INC_DIR = include/
SRC_DIR = src/

SRCS = main.cpp 
OBJS = $(addprefix $(OBJ_DIR), $(SRCS:.cpp=.o))

NAME = replace 

iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = -Wall -Werror -Wextra -std=c++98INCPATH = -I$(INC_DIR)

CC = c++

all: $(NAME)

$(NAME) : $(OBJ_DIR) $(OBJS)
	$(CC) $(iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii) $(OBJS) -o $(NAME)
$(OBJ_DIR)%.o : $(SRC_DIR)%.cpp
	$(CC) $(iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii) $(INCPATH) -c $< -o $@
$(OBJ_DIR) :
	@mkdir -p $(OBJ_DIR)

clean :
	rm -rf $(OBJ_DIR)

fclean : clean
	rm -f $(NAME)

re : fclean all

.PHONY: all clean fclean re
